openapi: 3.0.3
info:
  title: Quiz Application - OpenAPI 3.0
  version: 0.0.1-SNAPSHOT
tags:
  - name: quiz
    description: APIs for tests
  - name: auth
    description: APIs for authentication
  - name: admin
    description: APIs for admins
paths:
  /quiz:
    get:
      tags:
        - quiz
      summary: List of all tests
      operationId: getListOfTests
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: "number"
            format: "int32"
        - name: size
          in: query
          required: true
          schema:
            type: "number"
            format: "int32"
        - name: sortType
          in: query
          description: ASC, DESC
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/TestDTO'
    post:
      tags:
        - quiz
      summary: Submit test
      description: Submit all answers for the test and get result
      operationId: submitTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestAnswersDTO'
      responses:
        '200':
          description: Result for the test
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: "string"
        '400':
          description: Test or question are not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quiz/{testId}/comments:
    get:
      tags:
        - quiz
      summary: Get the list of comments for the test
      description: Get the list of comments for the test by id
      operationId: getTestComments
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestComment'
        '400':
          description: Test is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - quiz
      summary: Post comment for the test
      operationId: "writeComment"
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WriteCommentDTO'
      responses:
        '200':
          description: Successful uploading the comment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "number"
                    format: "int64"
        '400':
          description: Test is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quiz/{testId}/question:
    get:
      tags:
        - quiz
      summary: Get next question for the test
      description: Get question by testId and number of question
      operationId: getQuestion
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: q
          in: query
          required: true
          schema:
            type: "number"
            format: "int32"
      responses:
        '200':
          description: Successful uploading the comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionDTO'
        '400':
          description: Test or question are not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quiz/{testId}/rate:
    post:
      tags:
        - quiz
      summary: Rate test
      operationId: rateTest
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: rate
          in: query
          required: true
          schema:
            type: "number"
            format: "int32"
      responses:
        '200':
          description: Successful uploading the rate
        '400':
          description: Test is not found or invalid rate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quiz/{testId}:
    get:
      tags:
        - quiz
      summary: Get the number of questions in the test
      description: Get the number of questions in the test by id
      operationId: getQuestionsCount
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: "number"
                    format: "int64"
        '400':
          description: Test is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      tags:
        - auth
      summary: Sign in account
      description: Sign in with username and password
      operationId: authUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: "string"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/register:
    post:
      tags:
        - auth
      summary: Register new account
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: "string"
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /admin/quiz/{testId}:
    delete:
      tags:
        - admin
      summary: Delete test
      description: Delete test by id
      operationId: deleteTest
      parameters:
        - name: testId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        '200':
          description: Successful operation
        '404':
          description: Test is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /admin/user/{userId}:
    delete:
      tags:
        - admin
      summary: Delete person
      description: Delete person by id
      operationId: deletePerson
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        '200':
          description: Successful operation
        '404':
          description: User is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /admin/quiz:
    post:
      tags:
        - admin
      summary: Create new test
      operationId: createTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "number"
                    format: "int64"
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TestDTO:
      type: object
      properties:
        id:
          type: "number"
          format: "int64"
          nullable: false
        name:
          type: "string"
          nullable: false
        rate:
          type: "number"
          format: "double"
          nullable: false
    QuestionDTO:
      type: object
      properties:
        text:
          type: "string"
          nullable: false
        answers:
          type: "array"
          items:
            type: "string"
    Error:
      type: object
      properties:
        message:
          type: "string"
    WriteCommentDTO:
      type: object
      properties:
        comment:
          type: "string"
          nullable: false
    TestComment:
      type: object
      properties:
        id:
          type: "number"
          format: "int64"
          nullable: false
        writeDate:
          type: "string"
          format: "date-time"
          nullable: false
        writer:
          type: "string"
          nullable: false
        comment:
          type: "string"
          nullable: false
    TestAnswersDTO:
      type: object
      properties:
        testId:
          type: "number"
          format: "int64"
          nullable: false
        answers:
          $ref: '#/components/schemas/TestAnswer'
    LoginRequestDTO:
      type: object
      properties:
        username:
          type: "string"
          nullable: false
        password:
          type: "string"
          nullable: false
    RegisterRequestDTO:
      type: object
      properties:
        name:
          type: "string"
          nullable: false
        email:
          type: "string"
          nullable: false
        password:
          type: "string"
          nullable: false
    TestAnswer:
      type: object
      properties:
        questionId:
          type: "number"
          format: "int64"
          nullable: false
        answer:
          type: integer
          nullable: false
      example:
        1: 1
        2: 2
    CreateTestResutDTO:
      type: object
      properties:
        leftBound:
          type: "number"
          format: "int32"
          nullable: false
        rightBound:
          type: "number"
          format: "int32"
          nullable: false
        description:
          type: "string"
          nullable: false
    CreateAnswerDTO:
      type: object
      properties:
        rate:
          type: "number"
          format: "int32"
          nullable: false
        answer:
          type: "string"
          nullable: false
    CreateQuestionDTO:
      type: object
      properties:
        text:
          type: "string"
          nullable: false
        answers:
          type: "array"
          items:
            $ref: '#/components/schemas/CreateAnswerDTO'
    CreateTestDTO:
      type: object
      properties:
        name:
          type: "string"
          nullable: false
        questions:
          type: "array"
          items:
            $ref: '#/components/schemas/CreateQuestionDTO'
        results:
          type: "array"
          items:
            $ref: '#/components/schemas/CreateTestResutDTO'